### ISSUE TITLE
UNEXPECTED during `gzemnid fetch`

### ISSUE THREAD

**Issue by davisjam** [ChALkeR/Gzemnid#13]
Hit these UNEXPECTED during `gzemnid fetch`:

```
UNEXPECTED:  {"id":"testx2","key":"testx2"}
UNEXPECTED:  {"id":"zachtestproject2","key":"zachtestproject2"}
UNEXPECTED:  {"id":"zachtestproject3","key":"zachtestproject3"}
UNEXPECTED:  {"id":"zachtestproject4","key":"zachtestproject4"}
```

**Comment by ChALkeR** [comment]
Yes, that is known. Those are the packages with strange data in the registry, and those are ignored and not downloaded.

**Comment by ChALkeR** [comment]
It's an issue on the registry side, and Gzemnid just ignores those packages. The notice in the console is just so that other entries like that could be spotted easily.

I don't think there is anything else that could be done here.

**Comment by ChALkeR** [comment]
`npm install` for those packages also doesn't work, they are just broken in the registry.

**Comment by ChALkeR** [comment]
Closing as nothing has to be done here — let me know if you think otherwise.

**Comment by davisjam** [comment]
> Yes, that is known.

Then "UNEXPECTED" might not be the best error message.

**Comment by ChALkeR** [comment]
@davisjam Well, the registry is providing inconsistent data for those packages…
Perhaps I will reword the message.
